CU-1pdrzme_Show-associated-photos-in-event-details-page
Vancouver-KDD/kdd-website pull request #69
Opened 2021-11-17 06:27 UTC by bennettoh

- added more type specifications for photos
- utilize existing PhotoCard component to display related photos on event details page

2021-11-17 06:27 UTC, bennettoh commented
Task linked: [CU-1pdrzme Show associated photos in event details page](https://app.clickup.com/t/1pdrzme)

2021-11-18 10:00 UTC, bosung90 commented
@bennettoh Can you make the event photos 2 columns instead of 1 just like the photos page?

2021-11-20 20:38 UTC, bennettoh commented
@bosung90 Updated to have a responsive column layout! 
![image](https://user-images.githubusercontent.com/37195343/142740311-b057c40e-458b-49e2-adf8-6998120a2dde.png)
![image](https://user-images.githubusercontent.com/37195343/142740315-d64f5100-117b-469b-a2e6-788b14b1f850.png)

2021-11-22 00:15 UTC, bosung90 requested changes

2021-11-22 00:15 UTC, bosung90 commented on src/pages/EventDetailsPage.tsx
> +                                    <PhotoCard key={index} {...photo} />
key should be on the outer "Grid" element instead of PhotoCard

2021-11-22 00:15 UTC, bosung90 commented on src/types.ts
> +interface Photo {
This is nice! but would be nice to make this name more generic such as "Image" since we use it in many places.

2021-11-22 00:15 UTC, bosung90 commented on src/types.ts
> +        large: {
these formats are not guaranteed to exist. Put ? at the end of all sizes such as large? medium?

2021-11-22 00:15 UTC, bosung90 commented on src/types.ts
> +interface Photo {
Can you search for any[] where we used instead of images and use this interface instead?

2021-11-23 02:20 UTC, merged